 .gitignore                                     |   1 [32m+[m
 .lovable/plan.md                               |   0
 .lovable/project.json                          |   0
 .prettierignore                                |   0
 .prettierrc                                    |   0
 AGENTS.md                                      |   0
 bun.lock                                       |   0
 bunfig.toml                                    |   0
 components.json                                |   0
 db/setup.sql                                   |   0
 eslint.config.js                               |   0
 package.json                                   |   0
 public/favicon.ico                             | Bin [31m20373[m -> [32m20373[m bytes
 src/assets/audios/Desktop2026.mp3.asset.json   |   0
 src/assets/audios/aviso.mp3.asset.json         |   0
 src/assets/audios/buscaacordo.mp3.asset.json   |   0
 src/assets/audios/pagamento.mp3.asset.json     |   0
 src/assets/audios/parabens.mp3.asset.json      |   0
 src/assets/images/desenrola.png.asset.json     |   0
 src/assets/images/fundo.png.asset.json         |   0
 src/assets/images/iconefooter.png.asset.json   |   0
 src/assets/images/iconegov.png.asset.json      |   0
 src/assets/images/image1.png.asset.json        |   0
 src/assets/images/image2.png.asset.json        |   0
 src/assets/images/leticia.png.asset.json       |   0
 src/assets/images/limpenome.png.asset.json     |   0
 src/assets/images/logoamarelo.png.asset.json   |   0
 src/assets/images/score.jpg.asset.json         |   0
 src/assets/videos/video1.mp4.asset.json        |   0
 src/components/ui/accordion.tsx                |   0
 src/components/ui/alert-dialog.tsx             |   0
 src/components/ui/alert.tsx                    |   0
 src/components/ui/aspect-ratio.tsx             |   0
 src/components/ui/avatar.tsx                   |   0
 src/components/ui/badge.tsx                    |   0
 src/components/ui/breadcrumb.tsx               |   0
 src/components/ui/button.tsx                   |   0
 src/components/ui/calendar.tsx                 |   0
 src/components/ui/card.tsx                     |   0
 src/components/ui/carousel.tsx                 |   0
 src/components/ui/chart.tsx                    |   0
 src/components/ui/checkbox.tsx                 |   0
 src/components/ui/collapsible.tsx              |   0
 src/components/ui/command.tsx                  |   0
 src/components/ui/context-menu.tsx             |   0
 src/components/ui/dialog.tsx                   |   0
 src/components/ui/drawer.tsx                   |   0
 src/components/ui/dropdown-menu.tsx            |   0
 src/components/ui/form.tsx                     |   0
 src/components/ui/hover-card.tsx               |   0
 src/components/ui/input-otp.tsx                |   0
 src/components/ui/input.tsx                    |   0
 src/components/ui/label.tsx                    |   0
 src/components/ui/menubar.tsx                  |   0
 src/components/ui/navigation-menu.tsx          |   0
 src/components/ui/pagination.tsx               |   0
 src/components/ui/popover.tsx                  |   0
 src/components/ui/progress.tsx                 |   0
 src/components/ui/radio-group.tsx              |   0
 src/components/ui/resizable.tsx                |   0
 src/components/ui/scroll-area.tsx              |   0
 src/components/ui/select.tsx                   |   0
 src/components/ui/separator.tsx                |   0
 src/components/ui/sheet.tsx                    |   0
 src/components/ui/sidebar.tsx                  |   0
 src/components/ui/skeleton.tsx                 |   0
 src/components/ui/slider.tsx                   |   0
 src/components/ui/sonner.tsx                   |   0
 src/components/ui/switch.tsx                   |   0
 src/components/ui/table.tsx                    |   0
 src/components/ui/tabs.tsx                     |   0
 src/components/ui/textarea.tsx                 |   0
 src/components/ui/toggle-group.tsx             |   0
 src/components/ui/toggle.tsx                   |   0
 src/components/ui/tooltip.tsx                  |   0
 src/hooks/use-mobile.tsx                       |   0
 src/integrations/freepay/credentials.server.ts |   0
 src/integrations/supabase/client.server.ts     |   0
 src/lib/error-capture.ts                       |   0
 src/lib/error-page.ts                          |   0
 src/lib/lovable-error-reporting.ts             |   0
 src/lib/utils.ts                               |   0
 src/routeTree.gen.ts                           |   0
 src/router.tsx                                 |   0
 src/routes/README.md                           |   0
 src/routes/__root.tsx                          |   0
 src/routes/api/public/log/chat.ts              |   0
 src/routes/api/public/log/cpf.ts               |   0
 src/routes/api/public/pix/criar.ts             |   0
 src/routes/api/public/pix/status.ts            |   0
 src/routes/api/public/pix/webhook.ts           |   0
 src/routes/chat.tsx                            |   0
 src/routes/cpf.tsx                             |   0
 src/routes/index.tsx                           |   0
 src/routes/pagamento.tsx                       |   0
 src/server.ts                                  |   0
 src/start.ts                                   |   0
 src/styles.css                                 |   0
 tsconfig.json                                  |   0
 vite.config.ts                                 |   0
 100 files changed, 1 insertion(+)
