/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as CpfRouteImport } from './routes/cpf'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as Chat2RouteImport } from './routes/chat2'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AjusteRouteImport } from './routes/ajuste'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpsellTaxaCorretivaRouteImport } from './routes/upsell.taxa-corretiva'
import { Route as UpsellScorePlusRouteImport } from './routes/upsell.score-plus'
import { Route as UpsellImpostoConclusaoRouteImport } from './routes/upsell.imposto-conclusao'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as ApiPublicSiteContentRouteImport } from './routes/api/public/site-content'
import { Route as ApiPublicPixWebhookRouteImport } from './routes/api/public/pix/webhook'
import { Route as ApiPublicPixStatusRouteImport } from './routes/api/public/pix/status'
import { Route as ApiPublicPixCriarRouteImport } from './routes/api/public/pix/criar'
import { Route as ApiPublicLogCpfRouteImport } from './routes/api/public/log/cpf'
import { Route as ApiPublicLogChatRouteImport } from './routes/api/public/log/chat'
import { Route as ApiPublicCpfLookupRouteImport } from './routes/api/public/cpf/lookup'
import { Route as ApiPublicComprovanteUploadRouteImport } from './routes/api/public/comprovante/upload'
import { Route as ApiPublicAdminOnlineRouteImport } from './routes/api/public/admin/online'
import { Route as ApiPublicAdminMarkPaidRouteImport } from './routes/api/public/admin/mark-paid'
import { Route as ApiPublicAdminGatewayRouteImport } from './routes/api/public/admin/gateway'
import { Route as ApiPublicAdminDataRouteImport } from './routes/api/public/admin/data'
import { Route as ApiPublicAdminComprovanteRouteImport } from './routes/api/public/admin/comprovante'
import { Route as ApiPublicPixWebhookKlivoRouteImport } from './routes/api/public/pix/webhook/klivo'
import { Route as ApiPublicPixWebhookBlackcatRouteImport } from './routes/api/public/pix/webhook/blackcat'
import { Route as ApiPublicPixWebhookAlphaRouteImport } from './routes/api/public/pix/webhook/alpha'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const CpfRoute = CpfRouteImport.update({
  id: '/cpf',
  path: '/cpf',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const Chat2Route = Chat2RouteImport.update({
  id: '/chat2',
  path: '/chat2',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AjusteRoute = AjusteRouteImport.update({
  id: '/ajuste',
  path: '/ajuste',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpsellTaxaCorretivaRoute = UpsellTaxaCorretivaRouteImport.update({
  id: '/upsell/taxa-corretiva',
  path: '/upsell/taxa-corretiva',
  getParentRoute: () => rootRouteImport,
} as any)
const UpsellScorePlusRoute = UpsellScorePlusRouteImport.update({
  id: '/upsell/score-plus',
  path: '/upsell/score-plus',
  getParentRoute: () => rootRouteImport,
} as any)
const UpsellImpostoConclusaoRoute = UpsellImpostoConclusaoRouteImport.update({
  id: '/upsell/imposto-conclusao',
  path: '/upsell/imposto-conclusao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSiteContentRoute = ApiPublicSiteContentRouteImport.update({
  id: '/api/public/site-content',
  path: '/api/public/site-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPixWebhookRoute = ApiPublicPixWebhookRouteImport.update({
  id: '/api/public/pix/webhook',
  path: '/api/public/pix/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPixStatusRoute = ApiPublicPixStatusRouteImport.update({
  id: '/api/public/pix/status',
  path: '/api/public/pix/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPixCriarRoute = ApiPublicPixCriarRouteImport.update({
  id: '/api/public/pix/criar',
  path: '/api/public/pix/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLogCpfRoute = ApiPublicLogCpfRouteImport.update({
  id: '/api/public/log/cpf',
  path: '/api/public/log/cpf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLogChatRoute = ApiPublicLogChatRouteImport.update({
  id: '/api/public/log/chat',
  path: '/api/public/log/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCpfLookupRoute = ApiPublicCpfLookupRouteImport.update({
  id: '/api/public/cpf/lookup',
  path: '/api/public/cpf/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicComprovanteUploadRoute =
  ApiPublicComprovanteUploadRouteImport.update({
    id: '/api/public/comprovante/upload',
    path: '/api/public/comprovante/upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminOnlineRoute = ApiPublicAdminOnlineRouteImport.update({
  id: '/api/public/admin/online',
  path: '/api/public/admin/online',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminMarkPaidRoute = ApiPublicAdminMarkPaidRouteImport.update({
  id: '/api/public/admin/mark-paid',
  path: '/api/public/admin/mark-paid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminGatewayRoute = ApiPublicAdminGatewayRouteImport.update({
  id: '/api/public/admin/gateway',
  path: '/api/public/admin/gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminDataRoute = ApiPublicAdminDataRouteImport.update({
  id: '/api/public/admin/data',
  path: '/api/public/admin/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminComprovanteRoute =
  ApiPublicAdminComprovanteRouteImport.update({
    id: '/api/public/admin/comprovante',
    path: '/api/public/admin/comprovante',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPixWebhookKlivoRoute =
  ApiPublicPixWebhookKlivoRouteImport.update({
    id: '/klivo',
    path: '/klivo',
    getParentRoute: () => ApiPublicPixWebhookRoute,
  } as any)
const ApiPublicPixWebhookBlackcatRoute =
  ApiPublicPixWebhookBlackcatRouteImport.update({
    id: '/blackcat',
    path: '/blackcat',
    getParentRoute: () => ApiPublicPixWebhookRoute,
  } as any)
const ApiPublicPixWebhookAlphaRoute =
  ApiPublicPixWebhookAlphaRouteImport.update({
    id: '/alpha',
    path: '/alpha',
    getParentRoute: () => ApiPublicPixWebhookRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajuste': typeof AjusteRoute
  '/chat': typeof ChatRoute
  '/chat2': typeof Chat2Route
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/cpf': typeof CpfRoute
  '/inicio': typeof InicioRoute
  '/pagamento': typeof PagamentoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/upsell/imposto-conclusao': typeof UpsellImpostoConclusaoRoute
  '/upsell/score-plus': typeof UpsellScorePlusRoute
  '/upsell/taxa-corretiva': typeof UpsellTaxaCorretivaRoute
  '/api/public/site-content': typeof ApiPublicSiteContentRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/public/admin/comprovante': typeof ApiPublicAdminComprovanteRoute
  '/api/public/admin/data': typeof ApiPublicAdminDataRoute
  '/api/public/admin/gateway': typeof ApiPublicAdminGatewayRoute
  '/api/public/admin/mark-paid': typeof ApiPublicAdminMarkPaidRoute
  '/api/public/admin/online': typeof ApiPublicAdminOnlineRoute
  '/api/public/comprovante/upload': typeof ApiPublicComprovanteUploadRoute
  '/api/public/cpf/lookup': typeof ApiPublicCpfLookupRoute
  '/api/public/log/chat': typeof ApiPublicLogChatRoute
  '/api/public/log/cpf': typeof ApiPublicLogCpfRoute
  '/api/public/pix/criar': typeof ApiPublicPixCriarRoute
  '/api/public/pix/status': typeof ApiPublicPixStatusRoute
  '/api/public/pix/webhook': typeof ApiPublicPixWebhookRouteWithChildren
  '/api/public/pix/webhook/alpha': typeof ApiPublicPixWebhookAlphaRoute
  '/api/public/pix/webhook/blackcat': typeof ApiPublicPixWebhookBlackcatRoute
  '/api/public/pix/webhook/klivo': typeof ApiPublicPixWebhookKlivoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajuste': typeof AjusteRoute
  '/chat': typeof ChatRoute
  '/chat2': typeof Chat2Route
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/cpf': typeof CpfRoute
  '/inicio': typeof InicioRoute
  '/pagamento': typeof PagamentoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/upsell/imposto-conclusao': typeof UpsellImpostoConclusaoRoute
  '/upsell/score-plus': typeof UpsellScorePlusRoute
  '/upsell/taxa-corretiva': typeof UpsellTaxaCorretivaRoute
  '/api/public/site-content': typeof ApiPublicSiteContentRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/public/admin/comprovante': typeof ApiPublicAdminComprovanteRoute
  '/api/public/admin/data': typeof ApiPublicAdminDataRoute
  '/api/public/admin/gateway': typeof ApiPublicAdminGatewayRoute
  '/api/public/admin/mark-paid': typeof ApiPublicAdminMarkPaidRoute
  '/api/public/admin/online': typeof ApiPublicAdminOnlineRoute
  '/api/public/comprovante/upload': typeof ApiPublicComprovanteUploadRoute
  '/api/public/cpf/lookup': typeof ApiPublicCpfLookupRoute
  '/api/public/log/chat': typeof ApiPublicLogChatRoute
  '/api/public/log/cpf': typeof ApiPublicLogCpfRoute
  '/api/public/pix/criar': typeof ApiPublicPixCriarRoute
  '/api/public/pix/status': typeof ApiPublicPixStatusRoute
  '/api/public/pix/webhook': typeof ApiPublicPixWebhookRouteWithChildren
  '/api/public/pix/webhook/alpha': typeof ApiPublicPixWebhookAlphaRoute
  '/api/public/pix/webhook/blackcat': typeof ApiPublicPixWebhookBlackcatRoute
  '/api/public/pix/webhook/klivo': typeof ApiPublicPixWebhookKlivoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajuste': typeof AjusteRoute
  '/chat': typeof ChatRoute
  '/chat2': typeof Chat2Route
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/cpf': typeof CpfRoute
  '/inicio': typeof InicioRoute
  '/pagamento': typeof PagamentoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/upsell/imposto-conclusao': typeof UpsellImpostoConclusaoRoute
  '/upsell/score-plus': typeof UpsellScorePlusRoute
  '/upsell/taxa-corretiva': typeof UpsellTaxaCorretivaRoute
  '/api/public/site-content': typeof ApiPublicSiteContentRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/public/admin/comprovante': typeof ApiPublicAdminComprovanteRoute
  '/api/public/admin/data': typeof ApiPublicAdminDataRoute
  '/api/public/admin/gateway': typeof ApiPublicAdminGatewayRoute
  '/api/public/admin/mark-paid': typeof ApiPublicAdminMarkPaidRoute
  '/api/public/admin/online': typeof ApiPublicAdminOnlineRoute
  '/api/public/comprovante/upload': typeof ApiPublicComprovanteUploadRoute
  '/api/public/cpf/lookup': typeof ApiPublicCpfLookupRoute
  '/api/public/log/chat': typeof ApiPublicLogChatRoute
  '/api/public/log/cpf': typeof ApiPublicLogCpfRoute
  '/api/public/pix/criar': typeof ApiPublicPixCriarRoute
  '/api/public/pix/status': typeof ApiPublicPixStatusRoute
  '/api/public/pix/webhook': typeof ApiPublicPixWebhookRouteWithChildren
  '/api/public/pix/webhook/alpha': typeof ApiPublicPixWebhookAlphaRoute
  '/api/public/pix/webhook/blackcat': typeof ApiPublicPixWebhookBlackcatRoute
  '/api/public/pix/webhook/klivo': typeof ApiPublicPixWebhookKlivoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ajuste'
    | '/chat'
    | '/chat2'
    | '/checkout'
    | '/contato'
    | '/cpf'
    | '/inicio'
    | '/pagamento'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/upsell/imposto-conclusao'
    | '/upsell/score-plus'
    | '/upsell/taxa-corretiva'
    | '/api/public/site-content'
    | '/api/public/track'
    | '/api/public/admin/comprovante'
    | '/api/public/admin/data'
    | '/api/public/admin/gateway'
    | '/api/public/admin/mark-paid'
    | '/api/public/admin/online'
    | '/api/public/comprovante/upload'
    | '/api/public/cpf/lookup'
    | '/api/public/log/chat'
    | '/api/public/log/cpf'
    | '/api/public/pix/criar'
    | '/api/public/pix/status'
    | '/api/public/pix/webhook'
    | '/api/public/pix/webhook/alpha'
    | '/api/public/pix/webhook/blackcat'
    | '/api/public/pix/webhook/klivo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ajuste'
    | '/chat'
    | '/chat2'
    | '/checkout'
    | '/contato'
    | '/cpf'
    | '/inicio'
    | '/pagamento'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/upsell/imposto-conclusao'
    | '/upsell/score-plus'
    | '/upsell/taxa-corretiva'
    | '/api/public/site-content'
    | '/api/public/track'
    | '/api/public/admin/comprovante'
    | '/api/public/admin/data'
    | '/api/public/admin/gateway'
    | '/api/public/admin/mark-paid'
    | '/api/public/admin/online'
    | '/api/public/comprovante/upload'
    | '/api/public/cpf/lookup'
    | '/api/public/log/chat'
    | '/api/public/log/cpf'
    | '/api/public/pix/criar'
    | '/api/public/pix/status'
    | '/api/public/pix/webhook'
    | '/api/public/pix/webhook/alpha'
    | '/api/public/pix/webhook/blackcat'
    | '/api/public/pix/webhook/klivo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ajuste'
    | '/chat'
    | '/chat2'
    | '/checkout'
    | '/contato'
    | '/cpf'
    | '/inicio'
    | '/pagamento'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/upsell/imposto-conclusao'
    | '/upsell/score-plus'
    | '/upsell/taxa-corretiva'
    | '/api/public/site-content'
    | '/api/public/track'
    | '/api/public/admin/comprovante'
    | '/api/public/admin/data'
    | '/api/public/admin/gateway'
    | '/api/public/admin/mark-paid'
    | '/api/public/admin/online'
    | '/api/public/comprovante/upload'
    | '/api/public/cpf/lookup'
    | '/api/public/log/chat'
    | '/api/public/log/cpf'
    | '/api/public/pix/criar'
    | '/api/public/pix/status'
    | '/api/public/pix/webhook'
    | '/api/public/pix/webhook/alpha'
    | '/api/public/pix/webhook/blackcat'
    | '/api/public/pix/webhook/klivo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AjusteRoute: typeof AjusteRoute
  ChatRoute: typeof ChatRoute
  Chat2Route: typeof Chat2Route
  CheckoutRoute: typeof CheckoutRoute
  ContatoRoute: typeof ContatoRoute
  CpfRoute: typeof CpfRoute
  InicioRoute: typeof InicioRoute
  PagamentoRoute: typeof PagamentoRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  UpsellImpostoConclusaoRoute: typeof UpsellImpostoConclusaoRoute
  UpsellScorePlusRoute: typeof UpsellScorePlusRoute
  UpsellTaxaCorretivaRoute: typeof UpsellTaxaCorretivaRoute
  ApiPublicSiteContentRoute: typeof ApiPublicSiteContentRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  ApiPublicAdminComprovanteRoute: typeof ApiPublicAdminComprovanteRoute
  ApiPublicAdminDataRoute: typeof ApiPublicAdminDataRoute
  ApiPublicAdminGatewayRoute: typeof ApiPublicAdminGatewayRoute
  ApiPublicAdminMarkPaidRoute: typeof ApiPublicAdminMarkPaidRoute
  ApiPublicAdminOnlineRoute: typeof ApiPublicAdminOnlineRoute
  ApiPublicComprovanteUploadRoute: typeof ApiPublicComprovanteUploadRoute
  ApiPublicCpfLookupRoute: typeof ApiPublicCpfLookupRoute
  ApiPublicLogChatRoute: typeof ApiPublicLogChatRoute
  ApiPublicLogCpfRoute: typeof ApiPublicLogCpfRoute
  ApiPublicPixCriarRoute: typeof ApiPublicPixCriarRoute
  ApiPublicPixStatusRoute: typeof ApiPublicPixStatusRoute
  ApiPublicPixWebhookRoute: typeof ApiPublicPixWebhookRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpf': {
      id: '/cpf'
      path: '/cpf'
      fullPath: '/cpf'
      preLoaderRoute: typeof CpfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat2': {
      id: '/chat2'
      path: '/chat2'
      fullPath: '/chat2'
      preLoaderRoute: typeof Chat2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuste': {
      id: '/ajuste'
      path: '/ajuste'
      fullPath: '/ajuste'
      preLoaderRoute: typeof AjusteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell/taxa-corretiva': {
      id: '/upsell/taxa-corretiva'
      path: '/upsell/taxa-corretiva'
      fullPath: '/upsell/taxa-corretiva'
      preLoaderRoute: typeof UpsellTaxaCorretivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell/score-plus': {
      id: '/upsell/score-plus'
      path: '/upsell/score-plus'
      fullPath: '/upsell/score-plus'
      preLoaderRoute: typeof UpsellScorePlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell/imposto-conclusao': {
      id: '/upsell/imposto-conclusao'
      path: '/upsell/imposto-conclusao'
      fullPath: '/upsell/imposto-conclusao'
      preLoaderRoute: typeof UpsellImpostoConclusaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site-content': {
      id: '/api/public/site-content'
      path: '/api/public/site-content'
      fullPath: '/api/public/site-content'
      preLoaderRoute: typeof ApiPublicSiteContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pix/webhook': {
      id: '/api/public/pix/webhook'
      path: '/api/public/pix/webhook'
      fullPath: '/api/public/pix/webhook'
      preLoaderRoute: typeof ApiPublicPixWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pix/status': {
      id: '/api/public/pix/status'
      path: '/api/public/pix/status'
      fullPath: '/api/public/pix/status'
      preLoaderRoute: typeof ApiPublicPixStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pix/criar': {
      id: '/api/public/pix/criar'
      path: '/api/public/pix/criar'
      fullPath: '/api/public/pix/criar'
      preLoaderRoute: typeof ApiPublicPixCriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/log/cpf': {
      id: '/api/public/log/cpf'
      path: '/api/public/log/cpf'
      fullPath: '/api/public/log/cpf'
      preLoaderRoute: typeof ApiPublicLogCpfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/log/chat': {
      id: '/api/public/log/chat'
      path: '/api/public/log/chat'
      fullPath: '/api/public/log/chat'
      preLoaderRoute: typeof ApiPublicLogChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cpf/lookup': {
      id: '/api/public/cpf/lookup'
      path: '/api/public/cpf/lookup'
      fullPath: '/api/public/cpf/lookup'
      preLoaderRoute: typeof ApiPublicCpfLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/comprovante/upload': {
      id: '/api/public/comprovante/upload'
      path: '/api/public/comprovante/upload'
      fullPath: '/api/public/comprovante/upload'
      preLoaderRoute: typeof ApiPublicComprovanteUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/online': {
      id: '/api/public/admin/online'
      path: '/api/public/admin/online'
      fullPath: '/api/public/admin/online'
      preLoaderRoute: typeof ApiPublicAdminOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/mark-paid': {
      id: '/api/public/admin/mark-paid'
      path: '/api/public/admin/mark-paid'
      fullPath: '/api/public/admin/mark-paid'
      preLoaderRoute: typeof ApiPublicAdminMarkPaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/gateway': {
      id: '/api/public/admin/gateway'
      path: '/api/public/admin/gateway'
      fullPath: '/api/public/admin/gateway'
      preLoaderRoute: typeof ApiPublicAdminGatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/data': {
      id: '/api/public/admin/data'
      path: '/api/public/admin/data'
      fullPath: '/api/public/admin/data'
      preLoaderRoute: typeof ApiPublicAdminDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/comprovante': {
      id: '/api/public/admin/comprovante'
      path: '/api/public/admin/comprovante'
      fullPath: '/api/public/admin/comprovante'
      preLoaderRoute: typeof ApiPublicAdminComprovanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pix/webhook/klivo': {
      id: '/api/public/pix/webhook/klivo'
      path: '/klivo'
      fullPath: '/api/public/pix/webhook/klivo'
      preLoaderRoute: typeof ApiPublicPixWebhookKlivoRouteImport
      parentRoute: typeof ApiPublicPixWebhookRoute
    }
    '/api/public/pix/webhook/blackcat': {
      id: '/api/public/pix/webhook/blackcat'
      path: '/blackcat'
      fullPath: '/api/public/pix/webhook/blackcat'
      preLoaderRoute: typeof ApiPublicPixWebhookBlackcatRouteImport
      parentRoute: typeof ApiPublicPixWebhookRoute
    }
    '/api/public/pix/webhook/alpha': {
      id: '/api/public/pix/webhook/alpha'
      path: '/alpha'
      fullPath: '/api/public/pix/webhook/alpha'
      preLoaderRoute: typeof ApiPublicPixWebhookAlphaRouteImport
      parentRoute: typeof ApiPublicPixWebhookRoute
    }
  }
}

interface ApiPublicPixWebhookRouteChildren {
  ApiPublicPixWebhookAlphaRoute: typeof ApiPublicPixWebhookAlphaRoute
  ApiPublicPixWebhookBlackcatRoute: typeof ApiPublicPixWebhookBlackcatRoute
  ApiPublicPixWebhookKlivoRoute: typeof ApiPublicPixWebhookKlivoRoute
}

const ApiPublicPixWebhookRouteChildren: ApiPublicPixWebhookRouteChildren = {
  ApiPublicPixWebhookAlphaRoute: ApiPublicPixWebhookAlphaRoute,
  ApiPublicPixWebhookBlackcatRoute: ApiPublicPixWebhookBlackcatRoute,
  ApiPublicPixWebhookKlivoRoute: ApiPublicPixWebhookKlivoRoute,
}

const ApiPublicPixWebhookRouteWithChildren =
  ApiPublicPixWebhookRoute._addFileChildren(ApiPublicPixWebhookRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AjusteRoute: AjusteRoute,
  ChatRoute: ChatRoute,
  Chat2Route: Chat2Route,
  CheckoutRoute: CheckoutRoute,
  ContatoRoute: ContatoRoute,
  CpfRoute: CpfRoute,
  InicioRoute: InicioRoute,
  PagamentoRoute: PagamentoRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  UpsellImpostoConclusaoRoute: UpsellImpostoConclusaoRoute,
  UpsellScorePlusRoute: UpsellScorePlusRoute,
  UpsellTaxaCorretivaRoute: UpsellTaxaCorretivaRoute,
  ApiPublicSiteContentRoute: ApiPublicSiteContentRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  ApiPublicAdminComprovanteRoute: ApiPublicAdminComprovanteRoute,
  ApiPublicAdminDataRoute: ApiPublicAdminDataRoute,
  ApiPublicAdminGatewayRoute: ApiPublicAdminGatewayRoute,
  ApiPublicAdminMarkPaidRoute: ApiPublicAdminMarkPaidRoute,
  ApiPublicAdminOnlineRoute: ApiPublicAdminOnlineRoute,
  ApiPublicComprovanteUploadRoute: ApiPublicComprovanteUploadRoute,
  ApiPublicCpfLookupRoute: ApiPublicCpfLookupRoute,
  ApiPublicLogChatRoute: ApiPublicLogChatRoute,
  ApiPublicLogCpfRoute: ApiPublicLogCpfRoute,
  ApiPublicPixCriarRoute: ApiPublicPixCriarRoute,
  ApiPublicPixStatusRoute: ApiPublicPixStatusRoute,
  ApiPublicPixWebhookRoute: ApiPublicPixWebhookRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
